model: "cnmoro/Mistral-7B-Portuguese"
host: "localhost"
port: 8000
tensor-parallel-size: 1
tokenizer_mode: "auto"
trust_remote_code: true
dtype: "bfloat16"
quantization: "bitsandbytes"
gpu_memory_utilization: 0.85
max_model_len: 4096
max_num_seqs: 32
max_num_batched_tokens: 32
enforce_eager: true
